name: infinity
services:
  postgres:
    container_name: infinitydb
    image: postgres
    restart: always
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
